# AI Lab Assignment 02: Uninformed and Informed Search Algorithms

### Section: <span style = "color: blue; font-weight: 550; font-family: 'Times New Roman'">81<span>
### Group: <span style = "color: blue; font-weight: 550; font-family: 'Times New Roman'">2<span>
### Members: 
<p style = "color: blue; margin-left: 100px; font-weight: 550; font-family: 'Times New Roman'">Raihanah AlAli 223007420<p>
<p style = "color: blue; margin-left: 100px; font-weight: 550; font-family: 'Times New Roman'">Habiba Hany 223049808<p>
<p style = "color: blue; margin-left: 100px; font-weight: 550; font-family: 'Times New Roman'">Sarah Alawad 223043808<p>
<p style = "color: blue; margin-left: 100px; font-weight: 550; font-family: 'Times New Roman'">Dala'a Alsabt 223003684<p>

## Part 1: Iterative Deepening Search Algorithm

### 1. Problem Description

#### 8-puzzle
<p>The goal is to rearrange a 3 × 3 grid of numbered tiles (1 to 8) from a scrambled starting point to a specific goal state (ordered tiles).
</br> • The starting state is a grid with tiles arranged in a random way (as shown in the picture).
</br> • Goal State: The tiles are lined up in order of number (usually 1, 2, 3...) with the empty space at the end.
</br> • Operators: Move the empty space Up, Down, Left, or Right to switch it with a tile next to it.
</br> • The challenge is to figure out the order of moves that will get you to the goal state.</p>

### 2. Solution Description
<p>• How it works: IDS takes the best parts of Depth-First Search (DFS) and Breadth-First Search (BFS) and puts them together. It does a number of DFS searches, each one with a higher depth limit (L=0, 1, 2...). 
</br>• Steps: 
</br>1. Set the depth limit to 0. If the goal isn't found, raise the limit by 1.
</br>2. The algorithm looks at all the possible tile moves up to that depth at each limit.
</br>3. If the goal isn't reached by the current limit, it starts the search over with a deeper limit. 
</br></br>• Result: This makes sure that the algorithm is both Optimal (finds the solution with the fewest moves) and Complete, and it uses a lot less memory than BFS.</p>

### 3. Code Implemetantion

In [23]:
import numpy as np

### A. Problem Represetation

//Explanation how the problem is represented in the code

<p style = "font-weight: 550px; font-family: 'Times New Roman'; font-size: 20px">The problem is represented as a 2D array with 3 rows and 3 columns. The initial state consists of a random distribution of numbers from 1 to 8 and the empty cell will be 0 and could be in any place.
</br></br> The goal is represented as a 2D array with 3 rows and 3 columns. The numbers are in ascending order from 1 to 8 then last cell is the empty cell(0)</p>

<img src="initial-goal states.PNG" style = "margin-left: 90px"/>

In [24]:
# # 0 indicates the empty cell
initial_state = np.array(
    [[1,2,3],
     [0,4,6],
     [7,5,8]]
)

goal_state = np.array(
    [[1,2,3],
     [4,5,6],
     [7,8,0]]
)

### B. Algorithm Implementation

//The implementation of the algorithm

// Explanation how the algorithm is implemented based on the code. 
<p style = "font-weight: 550px; font-family: 'Times New Roman'; font-size: 20px">The path is a list of arrays in the order of movements. IDFS algorithm is similar to depth limited search but the difference is that IDFS increases the limit if the goal state is not found in the tree of states constructed by the limit. In IDFS and based on the location of the empty cells, each state is expanded to a specific number of next states. Next state is the state after moving one cell to the place empty cell. Only the cells that are around the empty cell horizontally or verticalls can be moved to the place of empty cell. Cells can not move diagonally. The algorithm keeps iterating until the solution is found.</p>

In [25]:
def move_bottom(temp_move, x, y): # replaces the empty cell with the bottom cell
    temp_move[x][y], temp_move[x+1][y] = temp_move[x+1][y], temp_move[x][y]
    return temp_move

def move_top(temp_move, x, y): # replaces the empty cell with the top cell
    temp_move[x][y], temp_move[x-1][y] = temp_move[x-1][y], temp_move[x][y]
    return temp_move

def move_left(temp_move, x, y): # replaces the empty cell with the left cell
    temp_move[x][y], temp_move[x][y-1] = temp_move[x][y-1], temp_move[x][y]
    return temp_move

def move_right(temp_move, x, y): # replaces the empty cell with the right cell
    temp_move[x][y], temp_move[x][y+1] = temp_move[x][y+1], temp_move[x][y]
    return temp_move

def get_next_moves(current_state): # gets the immediate possible next moves from the current state
 
    empty_space_x, empty_space_y = np.where(current_state == 0) # gets the location of the empty space
    # np.where(condition) returns an array not direct values. example: ([2], [2]) 
    empty_space_x = empty_space_x[0] 
    empty_space_y = empty_space_y[0]
    rows, columns = current_state.shape # gets the shape of the board
    
    next_moves = []
    if empty_space_x < rows-1: # checks for cells that are not in the last row
        #move the bottom cell
        next_moves.append(move_bottom(current_state.copy(), empty_space_x, empty_space_y))
        
    if empty_space_x > 0: # checks for cells that are not in the first row
        #move the top cell
        next_moves.append(move_top(current_state.copy(), empty_space_x, empty_space_y))
        
    if empty_space_y < columns-1: # checks for cells that are not in the last column
        #move the right cell
        next_moves.append(move_right(current_state.copy(), empty_space_x, empty_space_y))
        
    if empty_space_y > 0: # check for cells that are not in the first column
        #move the left cell
        next_moves.append(move_left(current_state.copy(), empty_space_x, empty_space_y))
   
    return next_moves    

def dls(initial_state, goal_state, iteration, visited=None, path=None): # implementation of depth limited search algorithm
    if path is None:
        path = []
    if visited is None:
        visited = set()
        
    path.append(initial_state) # adds the initial state to the path
    
    visited.add(np.array2string(initial_state)) # marks the state as visited
    
    if (initial_state == goal_state).all(): # checks all cells for equallity
        return path

    if iteration <= 0: # checks for reaching the limit
        path.pop() # removes the wrong state
        return None
        
    else:
        for move in get_next_moves(initial_state): # it iterates through all possible states from the current state
            if np.array2string(move) not in visited:
                next_move_path =  dls(move, goal_state, iteration-1, visited, path) #recursive call
                if next_move_path != None:
                    return next_move_path
        path.pop() # removes the wrong state
        return None

def idfs(initial_state, goal_state): # implementation of depth limited search algorithm

    max_depth = 0 # depth counter
    while True:
        path = dls(initial_state, goal_state, max_depth) #apply dls on the states with the limit specified by the depth counter
        if path != None: # solution is found
            return path, max_depth 
        max_depth += 1

    return path, max_depth             

### C. Solving Problem Using the algorithm

// This is where you will add the code to solve the problem using the implemented algorithm.

<p style = "font-weight: 550px; font-family: 'Times New Roman'; font-size: 20px">Get the path and maximum depth for last iteration by calling the idfs function. Then the path is printed in order, and the maximum depth is displayed.</p>

In [35]:
path, max_depth = idfs(initial_state, goal_state)
print("Path:")

for state in path:
    print(state)
    print()

print("Max_depth = {}".format(max_depth))

Path:
[[1 2 3]
 [0 4 6]
 [7 5 8]]

[[1 2 3]
 [4 0 6]
 [7 5 8]]

[[1 2 3]
 [4 5 6]
 [7 0 8]]

[[1 2 3]
 [4 5 6]
 [7 8 0]]

Max_depth = 3


## Part 2: Uniform Cost Search Algorithm.

### 1. Problem Description
<p>The goal is to find the shortest (and cheapest) way to get from Sibiu to Bucharest on a map of cities. Sibiu is the starting point. Goal State: Bucharest. Nodes and edges: Cities are nodes, and roads are edges with certain distances (costs). Challenge: Choosing the path with the shortest total distance from a number of options.</p>

<img src="UCS.JPG" style = "margin-left: 90px"/>

### 2. Solution Description
<p>UCS: Uniform Cost Search Mechanism: UCS always expands the node with the lowest total cost from the start by using a Priority Queue (heapq). Start at Sibiu (cost 0) and add neighbours to the edge. Then, keep popping the cheapest city and checking out its neighbours. To avoid cycles and extra paths, use an Explored Set. 
</br>• Result: The algorithm finds the best way to get from Rimnicu Vilcea to Pitesti, which costs 278 km, which is less than the other way through Fagaras (310 km).</p>

### 3. Code Implemetantion

In [27]:
# First code block can be used to declare libraries
import heapq

### A. Problem Represetation

The graph is represented as a **dictionary (adjacency list)**. Each key is a city (node), and its value is a list of `(cost, neighbor)` tuples representing roads and their distances.

| Edge | Distance (km) |
|------|---------------|
| Sibiu – Fagaras | 99 |
| Sibiu – Rimnicu Vilcea | 80 |
| Rimnicu Vilcea – Pitesti | 97 |
| Fagaras – Bucharest | 211 |
| Pitesti – Bucharest | 101 |

The roads are **undirected**, each edge is added in both directions.

In [28]:
#Add code to represent the problem (Example: graph or tree construction)

graph = {
    'Sibiu':           [(99,  'Fagaras'),          (80,  'Rimnicu Vilcea')],
    'Fagaras':         [(99,  'Sibiu'),             (211, 'Bucharest')],
    'Rimnicu Vilcea':  [(80,  'Sibiu'),             (97,  'Pitesti')],
    'Pitesti':         [(97,  'Rimnicu Vilcea'),    (101, 'Bucharest')],
    'Bucharest':       [(211, 'Fagaras'),           (101, 'Pitesti')]
}

START = 'Sibiu'
GOAL  = 'Bucharest'

### B. Algorithm Implementation

**Data structure used:** `heapq` 

Each entry in the queue is a tuple `(cost, node, path)`. The heap always keeps the **lowest-cost entry at the front**, so `heappop()` always gives us the cheapest city to explore next.

**Key components of the function:**
- `frontier` — the priority queue, starts with Sibiu at cost 0.
- `explored` — a set of cities already visited.
- `heappop` — removes and returns the cheapest city from the frontier.
- `heappush` — adds a neighboring city to the frontier with its updated cumulative distance.
- When Bucharest is popped, the function immediately returns.

In [29]:
#Add code here to implement the algorithm.

def ucs(graph, start, goal):
    # we start with cost 0 and a path containing only the start city
    frontier = [(0, start, [start])]

    # keeps track of cities we have already expanded
    explored = set()

    while frontier:
        # pop the city with the lowest cumulative distance
        cost, node, path = heapq.heappop(frontier)

        # if we already explored this city through a cheaper path , skip it
        if node in explored:
            continue

        # mark this city as explored
        explored.add(node)

        # goal test 
        if node == goal:
            return path, cost

        # expand neighbors: loop through all roads leaving this city
        for edge_cost, neighbor in graph[node]:
            if neighbor not in explored:
                # push neighbor with updated cumulative distance and extended path
                heapq.heappush(frontier,
                    (cost + edge_cost, neighbor, path + [neighbor]))

    # if the loop ends without finding the goal, no path exists
    return None, float('inf')

### C. Solving Problem Using the algorithm

We call `ucs()` with the graph, start city `'Sibiu'`, and goal city `'Bucharest'`.

**Two possible routes exist:**
- Sibiu → Fagaras → Bucharest: 99 + 211 = **310 km**
- Sibiu → Rimnicu Vilcea → Pitesti → Bucharest: 80 + 97 + 101 = **278 km**

UCS will always expand the cheapest frontier node first, so it finds the **278 km route** as optimal solution.

**The expected output:**
```
Path: Sibiu -> Rimnicu Vilcea -> Pitesti -> Bucharest
Total cost: 278
```

In [30]:
#Add code here that solves the problem using the algorithm
path, cost = ucs(graph, START, GOAL)

print(f"Path: {' -> '.join(path)}")
print(f"Total cost: {cost}")

Path: Sibiu -> Rimnicu Vilcea -> Pitesti -> Bucharest
Total cost: 278


## Part 3: Greedy Best First Search Algorithm

### 1. Problem Description
<p>The goal is to help a player find the best way to get to a treasure (the goal) on a game map. Beginning Point: Point A (h = 20). Goal State: The treasure is at point F (h = 0). Heuristic (h): The estimated straight-line distance from each node to the goal. Environment: A directed graph with weights where locations are nodes and paths are edges with specific travel costs</p>

<img src="GBFS.JPG"/>

### 2. Solution Description
<p>Mechanism: GBFS uses a Priority Queue to expand the node that appears to be closest to the goal based only on the heuristic value h (n). Steps: 1. Start at node A and evaluate neighbors based on their h values. 2. Always pick the neighbor with the smallest h (the one that "looks" closest to the treasure). 3. Use a Visited Set to ensure the player doesn't move in circles. Result: The algorithm follows the path A → C → E → D → F with a total path cost of 20, prioritizing nodes with lower heuristic values at each step.</p>

### 3. Code Implemetantion

In [31]:
# First code block can be used to declare libraries
import heapq

### A. Problem Represetation

The game map is represented as a weighted directed graph using an adjacency list,
where each key is a location (node) and its value is a list of (neighbor, cost) tuples.
A separate heuristic dictionary stores each node's estimated distance to the goal.

In [32]:
#Add code to represent the problem (Example: graph or tree construction)
graph = {
    'A': [('C', 2), ('B', 4)],
    'B': [('C', 5), ('D', 10)],
    'C': [('E', 3)],
    'D': [('F', 11)],
    'E': [('D', 4)],
    'F': []
}

heuristic = {
    'A': 20,
    'B': 16,
    'C': 14,
    'D': 11,
    'E': 15,
    'F': 0
}


### B. Algorithm Implementation

The GBFS algorithm is implemented using a min-heap (priority queue).
The function takes the graph, heuristic, start, and goal as parameters.
At each step, the node with the lowest heuristic value h(n) is selected and expanded.
A visited set is used to avoid revisiting nodes.
The function returns the final path and total cost once the goal is reached.

In [33]:
#Add code here to implement the algorithm.
def greedy_best_first_search(graph, heuristic, start, goal):
    open_list = []
    heapq.heappush(open_list, (heuristic[start], start, [start]))
    visited = set()
    print(f"Starting Greedy Best First Search from '{start}' to '{goal}'")
    print("=" * 50)
    while open_list:
        h_val, current, path = heapq.heappop(open_list)
        if current in visited:
            continue
        visited.add(current)
        print(f"Visiting: {current} | h(n) = {h_val} | Path so far: {' -> '.join(path)}")
        if current == goal:
            total_cost = 0
            for i in range(len(path) - 1):
                for neighbor, weight in graph[path[i]]:
                    if neighbor == path[i+1]:
                        total_cost += weight
                        break
            print("=" * 50)
            print(f"Goal '{goal}' reached!")
            print(f"Path: {' -> '.join(path)}")
            print(f"Total Cost: {total_cost}")
            return path, total_cost
        for neighbor, weight in graph[current]:
            if neighbor not in visited:
                heapq.heappush(open_list, (heuristic[neighbor], neighbor, path + [neighbor]))
    print("No path found!")
    return None, None

### C. Solving Problem Using the algorithm

Here we run the GBFS algorithm on our game map to find the path from the player's starting 
position (A) to the treasure (F). The algorithm uses the heuristic values to guide the search 
toward the goal.

In [34]:
#Add code here that solves the problem using the algorithm
start = 'A'
goal = 'F'
greedy_best_first_search(graph, heuristic, start, goal)

Starting Greedy Best First Search from 'A' to 'F'
Visiting: A | h(n) = 20 | Path so far: A
Visiting: C | h(n) = 14 | Path so far: A -> C
Visiting: E | h(n) = 15 | Path so far: A -> C -> E
Visiting: D | h(n) = 11 | Path so far: A -> C -> E -> D
Visiting: F | h(n) = 0 | Path so far: A -> C -> E -> D -> F
Goal 'F' reached!
Path: A -> C -> E -> D -> F
Total Cost: 20


(['A', 'C', 'E', 'D', 'F'], 20)